name = "iam_gleam_playground"
version = "1.0.0"

[dependencies]
gleam_erlang = ">= 0.26.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_httpc = ">= 2.3.0 and < 3.0.0"
gleam_stdlib = ">= 0.40.0 and < 2.0.0"
mist = ">= 2.0.0 and < 3.0.0"
wisp = ">= 1.1.0 and < 2.0.0"
radish = ">= 0.15.0 and < 1.0.0"
gleam_otp = ">= 0.12.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
